Neos:
  Starter:
    features:
      # this feature must come first; as it creates the baseline for all other features (e.g. defines the start
      # of the README)
      'Neos\Starter\Features\Neos\NeosFeature':
        position: 'start'

      # order is somehow relevant, because it makes the output deterministic (e.g. in README.md sections)
      'Neos\Starter\Features\Sites\NeosDemo\NeosDemoSiteFeature': true
      'Neos\Starter\Features\Deployment\DockerCompose\DockerComposeFeature': true
      'Neos\Starter\Features\Deployment\Redis\RedisFeature': true
      'Neos\Starter\Features\Packages\Seo\SeoFeature': true
